# Data Merging

In [ ]:
import pandas as pd
# Example datasets for data merging
# Dataset 1: Pakistani individual
data1 ={
'id': [1, 2, 4],
'name': ['Ahmed','Fatima','Ali'],
'age': [28,32, 24]
}
df1 = pd.DataFrame(data1)
df1.head()

   id    name  age
0   1   Ahmed   28
1   2  Fatima   32
2   3     Ali   24

In [10]:
data2 = {
    
    'id': [1, 2, 3],
    'city': ['Karachi', 'Lahore', 'Islamabad'],
    'occupation': ['Engineer', 'Doctor', 'Teacher']
}
df2 = pd.DataFrame(data2)
df2.head()

   id       city occupation
0   1    Karachi   Engineer
1   2     Lahore     Doctor
2   3  Islamabad    Teacher

In [11]:
# Merging Data frames on 'id'
merged_df=pd.merge(df1,df2,on='id',how='inner')
merged_df.head()

   id    name  age       city occupation
0   1   Ahmed   28    Karachi   Engineer
1   2  Fatima   32     Lahore     Doctor
2   3     Ali   24  Islamabad    Teacher