In [1]:
# Using templete data

In [6]:
import pandas as pd
import  numpy as np
import seaborn as sns

df = sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [8]:
# summary of data set
df.describe()

# column names
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [10]:
# Saving a dataframe to a csv file
df.to_csv("tips_save.csv", index=False)
df.to_excel("tips_save.xlsx", index=False)

In [14]:
# Using your own data
df = pd.read_csv("tips_save.csv")
df.head

df =pd.read_excel("tips_save.xlsx")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [15]:
# Save excel file in to computer D Drive
df.to_excel(r"D:\tips_save.xlsx", index=False)

In [22]:
# Reverse Row order
import pandas as pd
import seaborn as sns

df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [27]:
# Reverse Row order using loc method 
df.loc[::-1].head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True

In [28]:
# reset index 
df.loc[::-1].reset_index(drop=True).head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True
1,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
2,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
3,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
4,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True

In [29]:
# Reverse column order 
df.loc[:, ::-1].head()

,alone,alive,embark_town,deck,adult_male,who,class,embarked,fare,parch,sibsp,age,sex,pclass,survived
0,False,no,Southampton,NaN,True,man,Third,S,7.2500,0,1,22.0,male,3,0
1,False,yes,Cherbourg,C,False,woman,First,C,71.2833,0,1,38.0,female,1,1
2,True,yes,Southampton,NaN,False,woman,Third,S,7.9250,0,0,26.0,female,3,1
3,False,yes,Southampton,C,False,woman,First,S,53.1000,0,1,35.0,female,1,1
4,True,no,Southampton,NaN,True,man,Third,S,8.0500,0,0,35.0,male,3,0

In [32]:
# Select a column by data type 
df.dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [33]:
# Only select those having numeric data type
df.select_dtypes(include=["number"]).head()

   survived  pclass   age  sibsp  parch     fare
0         0       3  22.0      1      0   7.2500
1         1       1  38.0      1      0  71.2833
2         1       3  26.0      0      0   7.9250
3         1       1  35.0      1      0  53.1000
4         0       3  35.0      0      0   8.0500

In [ ]:
# Only select those having object type
df.select_dtypes(include=["object"]).head()

      sex embarked    who  embark_town alive
0    male        S    man  Southampton    no
1  female        C  woman    Cherbourg   yes
2  female        S  woman  Southampton   yes
3  female        S  woman  Southampton   yes
4    male        S    man  Southampton    no

In [42]:
# Only select those having multiple data type
df.select_dtypes(include=["object", "category", "number"]).head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,deck,embark_town,alive
0,0,3,male,22.0,1,0,7.2500,S,Third,man,NaN,Southampton,no
1,1,1,female,38.0,1,0,71.2833,C,First,woman,C,Cherbourg,yes
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,NaN,Southampton,yes
3,1,1,female,35.0,1,0,53.1000,S,First,woman,C,Southampton,yes
4,0,3,male,35.0,0,0,8.0500,S,Third,man,NaN,Southampton,no

In [44]:
df.select_dtypes(exclude=["object"]).head()

,survived,pclass,age,sibsp,parch,fare,class,adult_male,deck,alone
0,0,3,22.0,1,0,7.2500,Third,True,NaN,False
1,1,1,38.0,1,0,71.2833,First,False,C,False
2,1,3,26.0,0,0,7.9250,Third,False,NaN,True
3,1,1,35.0,1,0,53.1000,First,False,C,False
4,0,3,35.0,0,0,8.0500,Third,True,NaN,True

In [49]:
# Convert string to numbers
df= pd.DataFrame({"col A": ['1', '2', '3'], "col B": ['4', '5', '6']})
df

  col A col B
0     1     4
1     2     5
2     3     6

In [50]:
# check data types
df.dtypes

col A    object
col B    object
dtype: object

In [54]:
# Convert string to numbers
df.astype({"col A": "Float64", "col B": int}).dtypes

col A    Float64
col B      int32
dtype: object

In [55]:
# Convert string to numbers
df["col A"] = pd.to_numeric(df["col A"], errors="coerce")

In [56]:
# reduce data frame size 
df= sns.load_dataset("titanic")
df.shape

(891, 15)

In [58]:
df.sample(frac=0.1).shape

(89, 15)

In [59]:
# Copy data from clipboard 
# data set download 
import seaborn as sns
import pandas as pd

sns.load_dataset("titanic")
df.to_excel("titanic.xlsx")

In [60]:
# read from clipboard 
df = pd.read_clipboard()
df

     who  adult_male deck  embark_town
0    man        True  NaN  Southampton
1  woman       False    C    Cherbourg
2  woman       False  NaN  Southampton
3  woman       False    C  Southampton
4    man        True  NaN  Southampton
5    man        True  NaN   Queenstown

In [63]:
# Split dataset into 2 subsets
import pandas as pd
import seaborn as sns

df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [66]:
# check data number of rows
len(df)

891

In [67]:
# check data number of rows and columns
df.shape

(891, 15)

In [ ]:
# Randomly select 50% of the data 
titanic = df.sample(frac=0.5, random_state=1)
titanic.shape

(446, 15)

In [69]:
titanic_2=df.drop(titanic.index)
titanic_2.shape

(445, 15)

In [72]:
# Join 2 database 
df = pd.concat([titanic, titanic_2], axis=0)
df.shape

(891, 15)

In [8]:
# Filtring a database
import pandas as pd
import seaborn as sns
df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [9]:
# Filtering by column value
df.sex.unique()

array(['male', 'female'], dtype=object)

In [ ]:
# Filtering by column value and specific value 
df[(df.sex == "female")]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

In [15]:
# Filtering by column value and specific value 
df.embark_town.unique()
# Filtering by column(embark_town) and specific value
df[(df.embark_town == "Southampton")].shape

(644, 15)

In [ ]:
# multiple filtering - using AND operator filter-embark_town and sex-female only.
df[(df.embark_town == "Southampton")&
   (df.sex == "female")]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

In [22]:
# multiple filtering - using "OR" and "&" operator filter-embark_town (Southampton,Queenstown) seleclt in sex-female only. 
df[((df.embark_town == "Southampton")|
   (df.embark_town == "Queenstown"))&
   (df.sex == "female")]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

In [27]:
df[df.embark_town.isin(['Queenstown','Southampton'])].head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
# Filtering by age column value which is greater than > 30
df[df.age>30]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
873,0,3,male,47.0,0,0,9.0000,S,Third,man,True,NaN,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [30]:
# Filtering by age column value which is greater than < 30
df[df.age<30].shape

(384, 15)

In [ ]:
# filtring by large number of categories 
df.embark_town.value_counts()

embark_town
Southampton    644
Cherbourg      168
Queenstown      77
Name: count, dtype: int64

In [34]:
# filtring by large number of categories 
df.sex.value_counts()

sex
male      577
female    314
Name: count, dtype: int64

In [35]:
# filtring by large number of categories 
df.age.value_counts()

age
24.00    30
22.00    27
18.00    26
19.00    25
28.00    25
         ..
36.50     1
55.50     1
0.92      1
23.50     1
74.00     1
Name: count, Length: 88, dtype: int64

In [38]:
# filtring by large number of categories 
df.age.value_counts().nlargest(3)

age
24.0    30
22.0    27
18.0    26
Name: count, dtype: int64

In [39]:
# filtring by large number of categories 
counts=df.age.value_counts()
counts.nlargest(3)

age
24.0    30
22.0    27
18.0    26
Name: count, dtype: int64

In [40]:
# filtring by large number of categories 
counts=df.who.value_counts()
counts.nlargest(3)

who
man      537
woman    271
child     83
Name: count, dtype: int64

In [42]:
df[df.who.isin(counts.nlargest(3).index)].head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

**#16 - Splitting a string into multiple column**

In [45]:
import pandas as pd

df = pd.DataFrame({'name': ['Muhammad Waqas', 'Faisal Waheed', 'Shahbaz Gul', 'Imran Farooq'],
                   'location': ['Karachi, Pakistan', 'Faisalabad,Pakistan', 'Multan,Pakistan', 'Gujrat,Pakistan'],})
df

             name             location
0  Muhammad Waqas    Karachi, Pakistan
1   Faisal Waheed  Faisalabad,Pakistan
2     Shahbaz Gul      Multan,Pakistan
3    Imran Farooq      Gujrat,Pakistan

In [56]:
# Spliting a column into two column 
df.name.str.split(' ', expand = True)

          0       1
0  Muhammad   Waqas
1    Faisal  Waheed
2   Shahbaz     Gul
3     Imran  Farooq

In [57]:
# adding those splits into a column 
df[["first_name", "last_name"]] = df.name.str.split(' ', expand=True)
df

             name             location first_name last_name
0  Muhammad Waqas    Karachi, Pakistan   Muhammad     Waqas
1   Faisal Waheed  Faisalabad,Pakistan     Faisal    Waheed
2     Shahbaz Gul      Multan,Pakistan    Shahbaz       Gul
3    Imran Farooq      Gujrat,Pakistan      Imran    Farooq

# Location Expand

In [59]:
# Spliting a column into two column 
df.location.str.split(',', expand = True)

            0          1
0     Karachi   Pakistan
1  Faisalabad   Pakistan
2      Multan   Pakistan
3      Gujrat   Pakistan

In [62]:
# adding those-Location splits into a column 
df[["city_name", "country_name"]] = df.location.str.split(',', expand=True)
df

,name,location,first_name,last_name,city_name,country_name
0,Muhammad Waqas,"Karachi, Pakistan",Muhammad,Waqas,Karachi,Pakistan
1,Faisal Waheed,"Faisalabad,Pakistan",Faisal,Waheed,Faisalabad,Pakistan
2,Shahbaz Gul,"Multan,Pakistan",Shahbaz,Gul,Multan,Pakistan
3,Imran Farooq,"Gujrat,Pakistan",Imran,Farooq,Gujrat,Pakistan

In [64]:
# Refine data manipulation 
df= df [["first_name", "last_name", "city_name", "country_name"]]
df

  first_name last_name   city_name country_name
0   Muhammad     Waqas     Karachi     Pakistan
1     Faisal    Waheed  Faisalabad     Pakistan
2    Shahbaz       Gul      Multan     Pakistan
3      Imran    Farooq      Gujrat     Pakistan

# 17 Aggregate by multiple groups / functions

In [65]:
# libraries 
import pandas as pd
import seaborn as sns

# Import dataset 
df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [66]:
# Groupby Function 
df.groupby("who").count()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,deck,embark_town,alive,alone
who,,,,,,,,,,,,,,
child,83,83,83,83,83,83,83,83,83,83,13,83,83,83
man,537,537,537,413,537,537,537,537,537,537,99,537,537,537
woman,271,271,271,218,271,271,271,269,271,271,91,269,271,271

In [67]:
df.groupby("sex").count()

,survived,pclass,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
sex,,,,,,,,,,,,,,
female,314,314,261,314,314,314,312,314,314,314,97,312,314,314
male,577,577,453,577,577,577,577,577,577,577,106,577,577,577

In [71]:
df.groupby(["sex","pclass","class"]).count()

C:\Users\waqas.naseem\AppData\Local\Temp\ipykernel_108\1005450975.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["sex","pclass","class"]).count()

                      survived  age  sibsp  parch  fare  embarked  who  \
sex    pclass class
female 1      First         94   85     94     94    94        92   94
              Second         0    0      0      0     0         0    0
              Third          0    0      0      0     0         0    0
       2      First          0    0      0      0     0         0    0
              Second        76   74     76     76    76        76   76
              Third          0    0      0      0     0         0    0
       3      First          0    0      0      0     0         0    0
              Second         0    0      0      0     0         0    0
              Third        144  102    144    144   144       144  144
male   1      First        122  101    122    122   122       122  122
              Second         0    0      0      0     0         0    0
              Third          0    0      0      0     0         0    0
       2      First          0    0      0      0     0         0    0
              Second       108   99    108    108   108       108  108
              Third          0    0      0      0     0         0    0
       3      First          0    0      0      0     0         0    0
              Second         0    0      0      0     0         0    0
              Third        347  253    347    347   347       347  347

                      adult_male  deck  embark_town  alive  alone
sex    pclass class
female 1      First           94    81           92     94     94
              Second           0     0            0      0      0
              Third            0     0            0      0      0
       2      First            0     0            0      0      0
              Second          76    10           76     76     76
              Third            0     0            0      0      0
       3      First            0     0            0      0      0
              Second           0     0            0      0      0
              Third          144     6          144    144    144
male   1      First          122    94          122    122    122
              Second           0     0            0      0      0
              Third            0     0            0      0      0
       2      First            0     0            0      0      0
              Second         108     6          108    108    108
              Third            0     0            0      0      0
       3      First            0     0            0      0      0
              Second           0     0            0      0      0
              Third          347     6          347    347    347

# 18- Select Specific rows and columns

In [73]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [74]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
# Select 2 Columns sex and class 
df[["sex","class",]]

        sex   class
0      male   Third
1    female   First
2    female   Third
3    female   First
4      male   Third
..      ...     ...
886    male  Second
887  female   First
888  female   Third
889    male   First
890    male   Third

[891 rows x 2 columns]

In [76]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [78]:
# Select min, max, 25%, 50%, 75% values
# df.describe().loc[['min','25%','50%','75%','max']]

# Or 
df.describe().loc['min':'max']

     survived  pclass     age  sibsp  parch      fare
min       0.0     1.0   0.420    0.0    0.0    0.0000
25%       0.0     2.0  20.125    0.0    0.0    7.9104
50%       0.0     3.0  28.000    0.0    0.0   14.4542
75%       1.0     3.0  38.000    1.0    0.0   31.0000
max       1.0     3.0  80.000    8.0    6.0  512.3292

In [ ]:
# all values in between min and max values 
df.describe().loc['min':'max':]

     survived  pclass     age  sibsp  parch      fare
min       0.0     1.0   0.420    0.0    0.0    0.0000
25%       0.0     2.0  20.125    0.0    0.0    7.9104
50%       0.0     3.0  28.000    0.0    0.0   14.4542
75%       1.0     3.0  38.000    1.0    0.0   31.0000
max       1.0     3.0  80.000    8.0    6.0  512.3292

In [ ]:
# all values of survived between min and max values
df.describe().loc['min':'max','survived']

min    0.0
25%    0.0
50%    0.0
75%    1.0
max    1.0
Name: survived, dtype: float64

In [ ]:
# all values of survived and age between min and max values
df.describe().loc['min':'max',['survived','age']]

     survived     age
min       0.0   0.420
25%       0.0  20.125
50%       0.0  28.000
75%       1.0  38.000
max       1.0  80.000

In [ ]:
# all values of survived till age between min and max values
df.describe().loc['min':'max','survived':'age']

     survived  pclass     age
min       0.0     1.0   0.420
25%       0.0     2.0  20.125
50%       0.0     3.0  28.000
75%       1.0     3.0  38.000
max       1.0     3.0  80.000

# 19 - Reshape Multi index series

In [85]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
# mean of survived column
df.survived.mean()

0.3838383838383838

In [ ]:
# mean of survived column grouped by sex 
df.groupby("sex").survived.mean()

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

In [ ]:
# mean of survived column grouped by sex and class 
df.groupby(['sex','class']).survived.mean()

C:\Users\waqas.naseem\AppData\Local\Temp\ipykernel_108\1967038050.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['sex','class']).survived.mean()

sex     class
female  First     0.968085
        Second    0.921053
        Third     0.500000
male    First     0.368852
        Second    0.157407
        Third     0.135447
Name: survived, dtype: float64

In [ ]:
# mean of survived column grouped by sex and class - Unstacked
df.groupby(['sex','class']).survived.mean().unstack()

C:\Users\waqas.naseem\AppData\Local\Temp\ipykernel_108\3573713894.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['sex','class']).survived.mean().unstack()

class      First    Second     Third
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

# 20 - Continuos to Categorical data conversion

In [95]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [98]:
# values of age column
df.age.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [102]:
# creating bins for age column with 3 bins and labels as child, young and adult 
pd.cut(df.age, bins=[0, 18, 25, 99], labels = ['child', 'young', 'adult']).head()
df['new_age'] = pd.cut(df.age, bins=[0, 18, 25, 99], labels = ['child', 'young', 'adult'])
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,new_age
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,young
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,adult
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,adult
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,adult
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,adult

# 21 - convert one set values into another one

In [ ]:
# creating new column with value 1 for male and 0 for female 
df['sex_num'] = df.sex.map({'male': 1, 'female': 0})
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,new_age,sex_num
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,young,1
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,adult,0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,adult,0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,adult,0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,adult,1

In [107]:
df.embarked.unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [110]:
df['embarked_num'] = df.embarked.factorize()[0]
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,new_age,sex_num,embarked_num
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,0,no,False,young,1,0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,1,yes,False,adult,0,1
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,0,yes,True,adult,0,0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,0,yes,False,adult,0,0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,0,no,True,adult,1,0

# 22 Transpose a wide dataframe

In [111]:
import pandas as pd
import numpy as np

In [115]:
# Creating a new dataframe
df = pd.DataFrame(np.random.rand(200,25), columns=list('ABCDEFGHIJKLMNOPQRSTUVWXY'))
df.head()

,A,B,C,D,E,F,G,H,I,J,...,P,Q,R,S,T,U,V,W,X,Y
0,0.265475,0.935077,0.866782,0.111432,0.750076,0.766000,0.036829,0.686820,0.561149,0.423349,...,0.369386,0.089379,0.639742,0.744883,0.007928,0.743347,0.092344,0.470597,0.725816,0.009636
1,0.847442,0.045941,0.219393,0.838118,0.887653,0.509628,0.085977,0.174717,0.210665,0.328268,...,0.794410,0.130586,0.519532,0.025945,0.736474,0.928600,0.772798,0.433044,0.020882,0.426357
2,0.201169,0.476685,0.670497,0.421305,0.769784,0.648920,0.497052,0.680894,0.195505,0.053030,...,0.606125,0.626271,0.570763,0.223055,0.732852,0.375685,0.351589,0.279854,0.943799,0.424745
3,0.631431,0.353055,0.358121,0.789402,0.862264,0.592657,0.345730,0.768645,0.355711,0.483405,...,0.055393,0.175285,0.366544,0.206057,0.760530,0.117469,0.200926,0.692781,0.289186,0.199098
4,0.028237,0.790429,0.941607,0.354874,0.987715,0.157593,0.985835,0.319269,0.461293,0.774741,...,0.660626,0.093726,0.372412,0.843410,0.246780,0.337471,0.805528,0.081446,0.556180,0.084457

In [116]:
df.head().T

          0         1         2         3         4
A  0.265475  0.847442  0.201169  0.631431  0.028237
B  0.935077  0.045941  0.476685  0.353055  0.790429
C  0.866782  0.219393  0.670497  0.358121  0.941607
D  0.111432  0.838118  0.421305  0.789402  0.354874
E  0.750076  0.887653  0.769784  0.862264  0.987715
F  0.766000  0.509628  0.648920  0.592657  0.157593
G  0.036829  0.085977  0.497052  0.345730  0.985835
H  0.686820  0.174717  0.680894  0.768645  0.319269
I  0.561149  0.210665  0.195505  0.355711  0.461293
J  0.423349  0.328268  0.053030  0.483405  0.774741
K  0.300590  0.705955  0.571280  0.875663  0.015618
L  0.116084  0.790248  0.317175  0.645083  0.509372
M  0.316701  0.730215  0.229014  0.774923  0.657758
N  0.537992  0.415589  0.731576  0.093145  0.257966
O  0.685590  0.132129  0.782725  0.290637  0.469128
P  0.369386  0.794410  0.606125  0.055393  0.660626
Q  0.089379  0.130586  0.626271  0.175285  0.093726
R  0.639742  0.519532  0.570763  0.366544  0.372412
S  0.744883  0.025945  0.223055  0.206057  0.843410
T  0.007928  0.736474  0.732852  0.760530  0.246780
U  0.743347  0.928600  0.375685  0.117469  0.337471
V  0.092344  0.772798  0.351589  0.200926  0.805528
W  0.470597  0.433044  0.279854  0.692781  0.081446
X  0.725816  0.020882  0.943799  0.289186  0.556180
Y  0.009636  0.426357  0.424745  0.199098  0.084457

# 23 - Reshaping a data frame

In [ ]:
# Melt function 
df_melt = pd.melt(df.reset_index(), id_vars='index', value_vars=list(df.columns))
df_melt.head()

   index variable     value
0      0        A  0.265475
1      1        A  0.847442
2      2        A  0.201169
3      3        A  0.631431
4      4        A  0.028237